---
- hosts: all
  become: true
  tasks:
  - name: create docker image using war file
    command: docker build -t simple-devops-image .
    args:
      chdir: /opt/docker

  - name: create tag to docker image
    command: docker tag simple-devops-image goldentech/simple-devops-image

  - name: Log into DockerHub
    docker_login:
      username: goldentech
      password: Goldentech2016
      email: docker@docker.io
  - name: push image on to dockerhub
    command: docker push goldentech/simple-devops-image

  - name: remove docker images from ansible server
    command: docker rmi simple-devops-image:latest goldentech/simple-devops-image
    ignore_errors: yes